name: Release

on:
  push:
    tags: [ "*" ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
        with:
          cache-read-only: ${{ github.ref_type != 'tag' }}

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Publish to GitHub + Modrinth
        uses: Kira-NT/mc-publish@v3.3.0
        with:
          modrinth-id: betterthanmodern
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-generate-changelog: true

          game-version-filter: betas
          loaders: fabric, babric
          dependencies: |
            stationapi
            bh-creative(optional)
            beta-1.7.3-music-discs(optional)
